# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cgv-iOS-clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cgv-iOS-clone
  pod 'Moya', '~> 14.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0'

end
